### ISSUE TITLE
[BUG] Connected to voice channel clipping

### ISSUE THREAD

**Issue by Gibbu** [Slddev/SpotiCord#1]
### Client Mod

BetterDiscord

### Description of bug

When joining a voice channel, the associated controls are clipped through the "No song is playing" area.

### Steps to reproduce

- Use theme.
- Connect to voice channel.

### Screenshots

![image](https://user-images.githubusercontent.com/20338746/156905278-442ab22e-dd7d-443b-ba71-305e12123194.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
Will be fixed soon.

**Comment by Slddev** [comment]
Fixed.
