### ISSUE TITLE
[BUG] Spotify modal doesn't fill area and is scrollable

### ISSUE THREAD

**Issue by Rafii2198** [Slddev/SpotiCord#11]
### Client Mod

Powercord

### Description of bug

*It is for Replugged, there is no option for it, so I selected the precursor to that project.*

Using the Spotify Modal plugin, the designated area is not filled properly, the modal uses its original size and thus is scrollable

### Steps to reproduce

* Install this theme and SpotifyModal from [this link](https://discord.com/channels/1000926524452647132/1066241286409027595/1066241286409027595) which takes you to #plugin-links on Replugged Discord server
* Play any song on Spotify

### Suspected cause

**Big maybe** but as it was originally made for Powercord, it is not prepared for the new SpotifyModal for Replugged as it was completely rewritten. 
If it is the case, I know I should open another issue for it, but I'll do it here, could you make it, so the progress bar color uses `--sc-gradient-color` or `--background-accent` variable, so it will match with the rest theme?

### Screenshots

I took screenshot the area that should this modal fill, as you can see there is empty space
![image](https://github.com/Slddev/SpotiCord/assets/26695327/dfc8520b-9c99-4d05-a657-aa1d0d71e93c)
![image](https://github.com/Slddev/SpotiCord/assets/26695327/754638f0-6006-4a50-9558-dd752a668920)
And also one of full app
![image](https://github.com/Slddev/SpotiCord/assets/26695327/bbd562d0-b9a8-47d6-9fb4-20df8d7143a1)
*The purple color comes from my custom css, only thing I changed is 2 variables to make that color and only that so it can't be the cause*

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
That is how it is supposed to work.
