### ISSUE TITLE
[BUG] Message bar does not extend when it exceeds to next lines

### ISSUE THREAD

**Issue by moh-id** [Slddev/SpotiCord#12]
### Client Mod

Powercord, BetterDiscord

### Description of bug

When I'm typing a long paragraph, I expected the message bar to extend with the message exceeding to next lines. But instead the bar stayed the same and had the ability to scroll through the message. Its difficult like that to see what I've written. 

### Steps to reproduce

If you write a message which reaches next lines, the bar doesnt extend making it difficult to read what you typed.

### Suspected cause

Don't know the cause but probably an easy fix 

### Screenshots

![image](https://github.com/Slddev/SpotiCord/assets/141560832/7db46506-5021-4c11-b5a1-0f86d17f4390)
You can see in the image the next line is only slightly visible which requires me to scroll down making it difficult to understand what I typed before and after

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
The chat box is scrollable to see bigger messages.
