### ISSUE TITLE
[BUG] Message bar white

### ISSUE THREAD

**Issue by R1see** [Slddev/SpotiCord#2]
### Description of bug

The chat message bar should be black but its white

### Steps to reproduce

* Changing white message box to black

### Screenshots

![image](https://user-images.githubusercontent.com/62443062/157057955-a13d317e-cd6f-43c5-96ec-5660650eff28.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
The message bar is meant to be white.
