### ISSUE TITLE
[BUG] SpotifyControls clips when enlarge cover

### ISSUE THREAD

**Issue by UltLight** [Slddev/SpotiCord#3]
### Client Mod

BetterDiscord

### Description of bug

- What did I expect to happen?
when I enlarge the cover, the cover pops out instead of moving the controls down so I need to scroll

- What happened?
see screenshots

- why is it incorrect?
on the readme, it says that this theme is best used with the SpotifyControls plugin, so I expect it to work well with it

### Steps to reproduce

1. install SpotifyControls and BDFDB (required library)
2. play a song on spotify

### Screenshots

normal:
![Screenshot_196](https://user-images.githubusercontent.com/63460105/157239106-7d1f467a-539d-4cd4-8d61-85acb1f3766a.png)

when I enlarge the cover:
![Screenshot_197](https://user-images.githubusercontent.com/63460105/157239223-a151707e-39b3-43e3-8d9c-3ea8c20aabc6.png)

if I scroll down on the spotify controls area:
![Screenshot_198](https://user-images.githubusercontent.com/63460105/157239288-98fd424d-96ea-4311-8436-075919f5c0f4.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by harrykotten** [comment]
@Slddev  i have the same problem, did you come to a fix?
