### ISSUE TITLE
[BUG] raised userinfo 

### ISSUE THREAD

**Issue by Lewko6702** [Slddev/SpotiCord#4]
### Client Mod

Powercord

### Description of bug

this is weridly raised upwards and i can't seem to find a way to fix it any time i go out of settings it fixes for a split second than goes back

### Steps to reproduce

on launch

### Screenshots

![image](https://user-images.githubusercontent.com/45269833/167971249-cadaae25-abf8-4326-b0ca-5b63e7fbb06e.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
Fix may come late, very busy with personal stuff right now.

**Comment by Lewko6702** [comment]
No worries just wanted to make this known

**Comment by Slddev** [comment]
Fixed.
