### ISSUE TITLE
BUG - Release 0.3.3a still has "Now Playing" player on top of Activity Section?

### ISSUE THREAD

**Issue by joaomeuputo** [Slddev/SpotiCord#5]
### Client Mod

BetterDiscord

### Description of bug

Hey. 

So, on [releases](https://github.com/Slddev/SpotiCord/releases), there's version 0.1.3a and current version 0.3.3a.

Version 0.1.3a on Assets, has the .css file but 0.3.3a only has Source Code files. 
So I went and grabbed the Source Code from 0.3.3a and got the css file from that zip file, thinking that the source code would have the fixed version.

However, on Discord this issue still persists.
Am I missing something or is the 0.3.3a release really missing the fixed css file? 

Cheers man, awesome theme

### Steps to reproduce

- Download 0.3.3a Source Code file (or [BetterDiscord SpotiDiscord](https://betterdiscord.app/theme/SpotiCord)
- Apply the CSS file to BetterDiscord theme and enable it

### Screenshots

![imagem](https://user-images.githubusercontent.com/9698392/213592492-ebb6749e-6bfb-4729-946a-49e1d2f186a4.png)
![imagem](https://user-images.githubusercontent.com/9698392/213592430-eaf706cf-2bd5-4003-a474-ab8d23017860.png)
![imagem](https://user-images.githubusercontent.com/9698392/213592665-62a7fa8e-2a4b-4ebf-8b8d-87ddf8dd1e65.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
This is an intentional design. Please scroll to access the voice controls.
