### ISSUE TITLE
BUG - Release 0.3.3a text area not resizing with the text you're writing

### ISSUE THREAD

**Issue by joaomeuputo** [Slddev/SpotiCord#6]
### Client Mod

BetterDiscord

### Description of bug

I'm currently using 0.3.3a for BetterDiscord, and text input doesn't grow if you type more than 1 line of text.

### Steps to reproduce

- Install 0.3.3a release theme
- Insert 2 paragraphs and the text will "dissapear" from your view

### Screenshots

![imagem](https://user-images.githubusercontent.com/9698392/213595320-cf61b452-41e0-44d7-abec-4a430513f1b2.png)
![imagem](https://user-images.githubusercontent.com/9698392/213595333-de748af2-a1a5-4b51-ae25-b409954194ff.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
This is an intentional design. You are supposed to scroll through the text when there is too much characters.
